### ISSUE TITLE
Support building on MacOS

### ISSUE THREAD

**Issue by jeremiahpslewis** [MillenniumDB/MillenniumDB#2]
There seem to be a few minor things which prevent the project from building on MacOS, see:

https://gist.github.com/jeremiahpslewis/3066895f7827812ec1e30a3de15badfc#file-gistfile1-txt-L408
https://github.com/JuliaPackaging/Yggdrasil/pull/4057

**Comment by cirojas** [comment]
Thanks for reporting this issue,
For now there is no support for Macs because I have no experience or any type of access to Mac devices.
If there is a way to simulate the building in a Mac or if someone is willing to try changes until it works, I am willing to try to support it.

Your gist was useful to fix a couple of details, which are available in a new branch `feat/MacOS_building`, but there are surely more problems. A while ago someone else had a problem with `std::experimental::filesystem` and couldn't fix it, but it should be easy to fix as I only use it for basic things like knowing if a file exists or getting the file size, and I'm sure Macs have some way to handle that in C++.

**Comment by jeremiahpslewis** [comment]
Thanks! I'll try out the branch. The Julialang Yggdrasil platform is a nice place to build against MacOS with reproducible builds, I'll keep walking things through and report back as I hit issues (I'm not well-versed in Cxx so I won't be able to contribute in terms of a PR).

**Comment by jeremiahpslewis** [comment]
@cirojas Next error seems to be the following:

```bash
In file included from /workspace/srcdir/MillenniumDB/src/storage/page.cc:1:
In file included from /workspace/srcdir/MillenniumDB/src/storage/page.h:10:
/workspace/srcdir/MillenniumDB/src/storage/page_id.h:31:10: error: no type named 'size_t' in namespace 'std'
    std::size_t operator()(const PageId& k) const {
    ~~~~~^
1 error generated.
```

**Comment by cirojas** [comment]
We have decided that we'll focus only in linux x86-64 for the near future. We will think about supporting other architectures once we have our first production-ready release.
