### ISSUE TITLE
Instructions for importing data

### ISSUE THREAD

**Issue by szarnyasg** [MillenniumDB/MillenniumDB#3]
This is an exciting project, thanks for sharing it!

I was wondering about how to import data from CSV files. The README refers to file `tests/dbs/example-db.txt` but this does not exist.

**Comment by cirojas** [comment]
Hi @szarnyasg, thank you for opening this issue.

I didn't notice the example database was missing (its located in a .gitignore folder), in the commit a8ef438c062450cc1edac4054cc2ad10129e35a1 I added it.
The example file consist in 100k nodes + 500k connections with random data.

We don't support CSV for importing the data, instead we defined a custom text format (I think a .csv would be weird because each line has a different number or elements):

For the bulk import the engine reads a text file line by line, and each line can contain one of the following:
- A Node definition
- A Connection definition

In the node definition, a node identifier comes first, followed by a list of 0 or more Labels and finally a list of 0 or more properties, e.g:
`Joe :Person :Student age:20 Gender:"Male" Height:1.80 key_1:true`
In this case a node is being created with the node identifier `Joe` with the labels `Person` and `Student`, and the properties `age`, `gender`, `height` and `key_1`.
The supported property types are int, float, string and bool.

In the connection definition there are 2 node identifiers or literals associated with an arrow (`->` or `<-`), followed by the type of the connection (which is a `:` + node identifier) and finally a list of 0 or more properties
Examples:
`Joe->John :Follows`
`Joe->"Hello world" :Posted date:"06-10-2010"`
`Joe->20 :Age`

Nodes do not necessarily have to be defined to be used in a connection.

We also make a distinction between node identifier and a literal of string type, e.g:
`"Joe"` is different from `Joe`

Important: node identifiers, property keys and labels must belong to the set of strings defined by the regular language:
`[A-Za-z][A-Za-z0-9_] *`
